version: 2.0

jobs:

  refresh_geckoboard:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/directory-periodical-tests
    steps:
      - checkout
      - run:
          name: Refresh Geckoboard
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -r requirements_geckoboard_updater.txt
            python geckoboard_updater/geckoboard_updater.py

  check_for_dead_links_on_dev:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/directory-periodical-tests
    steps:
      - checkout
      - run:
          name: Check for dead links
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -r requirements_dead_links.txt
            TEST_ENV=DEV make dead_links_check
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports

  check_for_dead_links_on_stage:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/directory-periodical-tests
    steps:
      - checkout
      - run:
          name: Check for dead links
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -r requirements_dead_links.txt
            TEST_ENV=STAGE make dead_links_check
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports

  check_for_dead_links_on_prod:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/directory-periodical-tests
    steps:
      - checkout
      - run:
          name: Check for dead links
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -r requirements_dead_links.txt
            TEST_ENV=PROD make dead_links_check
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports

  accessibility_tests_export_readiness_dev:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/directory-periodical-tests
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install --yes --force-yes xmlstarlet parallel python-pip
            sudo pip install beautifulsoup4
            sudo npm install -g pa11y pa11y-reporter-html
      - run:
          name: Get XML sitemap
          command: |
            wget -q https://dev.exportreadiness.directory.uktrade.io/sitemap.xml
      - run:
          name: Convert XML sitemap to a TXT sitemap
          command: |
            xmlstarlet sel -N x="http://www.sitemaps.org/schemas/sitemap/0.9" -t -v "/x:urlset/x:url/x:loc" sitemap.xml > sitemap.txt
      - run:
          name: Scan URLs from TXT sitemap with Pa11y
          command: |
            echo "Pa11y will scan following URLs:"
            cat sitemap.txt
            parallel 'pa11y --reporter=html {} > {= s:[/\:\?\&\=]:-:g; =}.html' < sitemap.txt
      - run:
          name: Generate an index file for Pa11y html reports
          command: |
            python3 pa11y/generate-report-index.py
      - store_test_results:
          path: ./*.html
      - store_artifacts:
          path: ./*.html

workflows:
  version: 2

  refresh_geckoboard_periodically:
    triggers:
    - schedule:
        cron: "0,15,30,45 8-17 * * 1-5"
        filters:
          branches:
            only: master
    jobs:
      - refresh_geckoboard

  dev_check_for_dead_links:
    triggers:
    - schedule:
        cron: "0,30 8-17 * * 1-5"
        filters:
          branches:
            only: master
    jobs:
      - check_for_dead_links_on_dev

  stage_check_for_dead_links:
    triggers:
    - schedule:
        cron: "10,40 8-17 * * 1-5"
        filters:
          branches:
            only: master
    jobs:
      - check_for_dead_links_on_stage

  prod_check_for_dead_links:
    triggers:
    - schedule:
        cron: "20,50 8-17 * * 1-5"
        filters:
          branches:
            only: master
    jobs:
      - check_for_dead_links_on_prod

  dev_ex_read_accessibility_tests:
    triggers:
    - schedule:
        cron: "0,10,20,30,40,50 8-17 * * 1-5"
        filters:
          branches:
            only: master
    jobs:
      - accessibility_tests_export_readiness_dev
