# -*- coding: utf-8 -*-
import os

DIRECTORY_CMS_API_CLIENT_BASE_URL = os.environ[
    "DIRECTORY_CMS_API_CLIENT_BASE_URL"
]
DIRECTORY_CMS_API_CLIENT_API_KEY = os.environ[
    "DIRECTORY_CMS_API_CLIENT_API_KEY"
]
DIRECTORY_CMS_API_PAGES_ENDPOINT = os.getenv(
    "DIRECTORY_CMS_API_PAGES_ENDPOINT", "api/pages/"
)
